/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:      '#3525cd',
        'primary-dark': '#2318a8',
        'primary-light': '#4f46e5',
        'primary-faint': '#e2dfff',
        'primary-muted': '#c3c0ff',
        accent:       '#f97316',
        surface:      '#f8f9fa',
        'surface-card': '#ffffff',
        'surface-low':  '#f3f4f5',
        'surface-mid':  '#edeeef',
        'surface-high': '#e7e8e9',
        'on-surface':   '#191c1d',
        'on-muted':     '#464555',
        border:       '#c7c4d8',
        'border-dark':  '#777587',
        success:      '#15803d',
        'success-bg': '#dcfce7',
        warning:      '#92400e',
        'warning-bg': '#ffedd5',
        danger:       '#ba1a1a',
        'danger-bg':  '#ffdad6',
      },
      fontFamily: {
        display: ['"DM Serif Display"', 'Georgia', 'serif'],
        sans:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        sm:   '6px',
        DEFAULT: '10px',
        md:   '14px',
        lg:   '18px',
        xl:   '24px',
        full: '9999px',
      },
      boxShadow: {
        card:   '0 1px 3px rgba(0,0,0,.06), 0 4px 12px rgba(0,0,0,.04)',
        hover:  '0 4px 16px rgba(53,37,205,.12)',
        modal:  '0 20px 60px rgba(0,0,0,.18)',
        btn:    '0 4px 14px rgba(53,37,205,.28)',
      },
      keyframes: {
        fadeUp:  { from: { opacity: 0, transform: 'translateY(12px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        fadeIn:  { from: { opacity: 0 }, to: { opacity: 1 } },
        scaleIn: { from: { opacity: 0, transform: 'scale(.95)' }, to: { opacity: 1, transform: 'scale(1)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        spin:    { to: { transform: 'rotate(360deg)' } },
        slideRight: { from: { transform: 'translateX(-100%)', opacity: 0 }, to: { transform: 'translateX(0)', opacity: 1 } },
      },
      animation: {
        fadeUp:     'fadeUp .35s ease both',
        fadeIn:     'fadeIn .25s ease both',
        scaleIn:    'scaleIn .25s ease both',
        shimmer:    'shimmer 1.6s linear infinite',
        spin:       'spin .7s linear infinite',
        slideRight: 'slideRight .3s ease both',
      },
    },
  },
  plugins: [],
}
